transit:
  t0: 0.0                 # time of inferior conjunction (you can change if needed)
  per: 74.92768653        # orbital period in days
  rp: 0.0644              # planet radius (in stellar radii)
  a: 79.53                # semi-major axis (in stellar radii)
  inc: 89.47              # orbital inclination (degrees)
  ecc: 0.0                # eccentricity
  w: 90.0                 # argument of periastron (irrelevant for e=0)
  u: [0.3, 0.1]           # example limb darkening (adjust if you have better values)
  limb_dark: "quadratic"
classifier:
  type: cnn # [cnn, rf] for Convolutional Neural Network and Random Forest
#assignmnet2 taskG
detection:
  method: rf                 # optional label, not used by code but informative
  kernel: default_rf         # name of the RF configuration
  csv_path: tess_data.csv    # <<< dataset path (required in the assignment)
  n_bins: 1000
  use_scaler: false
  samples_per_class: 350
  n_estimators: 500
  max_depth: null
#task h assignment 2
detection:
  kernel: cnn          # or "rf" when you want RF by default (not used by CLI, but good documentation)
  csv_path: tess_data.csv
  n_bins: 1000
  use_scaler: true
  samples_per_class: 350

  # CNN-specific hyperparameters (Task H)
  epochs: 20
  batch_size: 64
  learning_rate: 0.001
#assignmnet2 Task I
dream:
  dataset_path: "/ca25/comp_astro_25/tess_data.csv"   # path to your lightcurve CSV
  label_column: "label"                    # or remove if there is no label column

  batch_size: 128
  z_dim: 100
  ngf: 32
  ndf: 32
  epochs: 100
  learning_rate: 0.0002
  beta1: 0.5

  model_dir: "models/gan"
  sample_output: "assignment2_taskI_dream.png"
